import "./lib/error-capture";

import { consumeLastCapturedError } from "./lib/error-capture";
import { renderErrorPage } from "./lib/error-page";

type ServerEntry = {
  fetch: (request: Request, env: unknown, ctx: unknown) => Promise<Response> | Response;
};

let serverEntryPromise: Promise<ServerEntry> | undefined;

/**
 * Lazily load the TanStack Start server entry.
 *
 * Keeping this cached prevents importing the server entry repeatedly
 * for every request within the same server instance.
 */
async function getServerEntry(): Promise<ServerEntry> {
  if (!serverEntryPromise) {
    console.log("[server-entry] Loading TanStack server entry...");

    serverEntryPromise = import("@tanstack/react-start/server-entry").then((m) => {
      console.log("[server-entry] TanStack server entry loaded.");

      return (m.default ?? m) as ServerEntry;
    });
  }

  return serverEntryPromise;
}

/**
 * Convert a value into a JSON Response.
 */
function jsonResponse(data: unknown, init: ResponseInit = {}): Response {
  return new Response(JSON.stringify(data), {
    ...init,
    headers: {
      "content-type": "application/json; charset=utf-8",
      ...(init.headers ?? {}),
    },
  });
}

/**
 * h3 can swallow certain in-handler exceptions and return a normal
 * HTTP 500 response containing:
 *
 * {"unhandled":true,"message":"HTTPError"}
 *
 * In that situation a normal try/catch around handler.fetch() will
 * not receive the original exception.
 */
async function normalizeCatastrophicSsrResponse(response: Response): Promise<Response> {
  if (response.status < 500) {
    return response;
  }

  const contentType = response.headers.get("content-type") ?? "";

  if (!contentType.includes("application/json")) {
    return response;
  }

  const body = await response.clone().text();

  if (!isH3SwallowedErrorBody(body)) {
    return response;
  }

  console.error(
    "[server] h3 swallowed SSR error:",
    consumeLastCapturedError() ?? new Error(`h3 swallowed SSR error: ${body}`),
  );

  return new Response(renderErrorPage(), {
    status: 500,
    headers: {
      "content-type": "text/html; charset=utf-8",
    },
  });
}

/**
 * Detect the generic error response generated by h3.
 */
function isH3SwallowedErrorBody(body: string): boolean {
  try {
    const payload = JSON.parse(body) as {
      unhandled?: unknown;
      message?: unknown;
    };

    return payload.unhandled === true && payload.message === "HTTPError";
  } catch {
    return false;
  }
}

/**
 * Handle POST /api/login
 */
async function handleLoginApi(request: Request): Promise<Response> {
  const { handleLoginRequest } = await import("@/lib/auth-api");

  return handleLoginRequest(request);
}

/**
 * Handle POST /api/register
 */
async function handleRegisterApi(request: Request): Promise<Response> {
  try {
    const payload = (await request.json()) as {
      name?: string;
      email?: string;
      password?: string;
    };

    const { registerUser } = await import("@/lib/auth-api");

    const result = await registerUser(
      String(payload.name ?? ""),
      String(payload.email ?? ""),
      String(payload.password ?? ""),
    );

    return jsonResponse(result, {
      status: result.success ? 201 : 400,
    });
  } catch (error) {
    console.error("[server-register] handler error:", error);

    return jsonResponse(
      {
        success: false,
        message: "Unable to create your account right now.",
      },
      {
        status: 500,
      },
    );
  }
}

/**
 * Main server entry.
 */
export default {
  async fetch(request: Request, env: unknown, ctx: unknown) {
    const requestId = crypto.randomUUID();

    console.log("[server] START", {
      requestId,
      method: request.method,
      url: request.url,
    });

    try {
      const url = new URL(request.url);

      console.log("[server] PATH", {
        requestId,
        pathname: url.pathname,
      });

      /**
       * Login API
       */
      if (request.method === "POST" && url.pathname === "/api/login") {
        console.log("[server] LOGIN", {
          requestId,
        });

        return await handleLoginApi(request);
      }

      /**
       * Register API
       */
      if (request.method === "POST" && url.pathname === "/api/register") {
        console.log("[server] REGISTER", {
          requestId,
        });

        return await handleRegisterApi(request);
      }

      /**
       * Everything else goes through TanStack Start.
       */
      console.log("[server] BEFORE SERVER ENTRY", {
        requestId,
      });

      const handler = await getServerEntry();

      console.log("[server] SERVER ENTRY LOADED", {
        requestId,
      });

      /**
       * Let TanStack Start handle the actual request.
       */
      const response = await handler.fetch(request, env, ctx);

      console.log("[server] HANDLER RESPONSE", {
        requestId,
        status: response.status,
        contentType: response.headers.get("content-type"),
      });

      /**
       * Normalize swallowed SSR errors.
       */
      const normalizedResponse = await normalizeCatastrophicSsrResponse(response);

      console.log("[server] COMPLETE", {
        requestId,
        status: normalizedResponse.status,
      });

      return normalizedResponse;
    } catch (error) {
      console.error("[server] FATAL REQUEST ERROR", {
        requestId,
        error,
      });

      return new Response(renderErrorPage(), {
        status: 500,
        headers: {
          "content-type": "text/html; charset=utf-8",
        },
      });
    }
  },
};
